In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
from google.colab import files
uploaded= files.upload()
uploaded1 =files.upload()
uploaded2 =files.upload()

Saving train.csv to train.csv


Saving test.csv to test.csv


Saving gender_submission.csv to gender_submission.csv


In [0]:
import io
train = pd.read_csv(io.BytesIO(uploaded['train.csv']))
test = pd.read_csv(io.BytesIO(uploaded1['test.csv']))
gs= pd.read_csv(io.BytesIO(uploaded2['gender_submission.csv']))

In [0]:
train['Age'] = train['Age'].fillna(0)
test['Age'] = test['Age'].fillna(0)

In [0]:
X = train.iloc[:, [2,4,5]].values
X_test = test.iloc[:, [1,3,4]].values

y = train.iloc[:, 1].values
y_test=gs.iloc[:, [1]].values

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 1] = labelencoder.fit_transform(X[:, 1])
labelencoder1 = LabelEncoder()
X_test[:, 1] = labelencoder1.fit_transform(X_test[:, 1])

In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [8]:
classifier = Sequential()
#Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu',input_dim = 3)) 
classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu')) 
#classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu'))
#Addind the output layer
classifier.add(Dense(output_dim = 1,init = 'uniform', activation = 'sigmoid')) 
#Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# Fitting the ANN to the Training set
classifier.fit(X,y,batch_size = 10,epochs = 100)

W0810 05:26:09.605917 139817270232960 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=3, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
W0810 05:26:09.684231 139817270232960 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0810 05:26:09.694295 139817270232960 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

/

Epoch 1/100
891/891 [==============================] - 1s 935us/step - loss: 0.6868 - acc: 0.6162
Epoch 2/100
891/891 [==============================] - 0s 121us/step - loss: 0.6691 - acc: 0.6162
Epoch 3/100
891/891 [==============================] - 0s 127us/step - loss: 0.6635 - acc: 0.6162
Epoch 4/100
891/891 [==============================] - 0s 116us/step - loss: 0.6589 - acc: 0.6162
Epoch 5/100
891/891 [==============================] - 0s 114us/step - loss: 0.6502 - acc: 0.6162
Epoch 6/100
891/891 [==============================] - 0s 116us/step - loss: 0.6405 - acc: 0.6162
Epoch 7/100
891/891 [==============================] - 0s 111us/step - loss: 0.6289 - acc: 0.6162
Epoch 8/100
891/891 [==============================] - 0s 125us/step - loss: 0.6146 - acc: 0.6162
Epoch 9/100
891/891 [==============================] - 0s 110us/step - loss: 0.5989 - acc: 0.6285
Epoch 10/100
891/891 [==============================] - 0s 111us/step - loss: 0.5822 - acc: 0.6891
Epoch 11/100
891/89

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [0]:
y_pred = (y_pred>0.5)

In [28]:
y_pred

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[266,   0],
       [ 32, 120]])

In [0]:
#After feature engineering with alone or with family

In [0]:
train['Alone'] = train.SibSp + train.Parch
test['Alone'] =  test.SibSp + test.Parch

In [15]:
train.head()

PassengerId  Survived  Pclass  ... Cabin Embarked  Alone
0            1         0       3  ...   NaN        S      1
1            2         1       1  ...   C85        C      1
2            3         1       3  ...   NaN        S      0
3            4         1       1  ...  C123        S      1
4            5         0       3  ...   NaN        S      0

[5 rows x 13 columns]

In [16]:
train['Alone'].loc[train['Alone']>0] = 1
train['Alone'].loc[train['Alone']==0] = 0
test['Alone'].loc[test['Alone']>0] = 1
test['Alone'].loc[test['Alone']==0] = 0

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [17]:
train.head()

PassengerId  Survived  Pclass  ... Cabin Embarked  Alone
0            1         0       3  ...   NaN        S      1
1            2         1       1  ...   C85        C      1
2            3         1       3  ...   NaN        S      0
3            4         1       1  ...  C123        S      1
4            5         0       3  ...   NaN        S      0

[5 rows x 13 columns]

In [18]:
test.head()

PassengerId  Pclass  ... Embarked Alone
0          892       3  ...        Q     0
1          893       3  ...        S     1
2          894       2  ...        Q     0
3          895       3  ...        S     0
4          896       3  ...        S     1

[5 rows x 12 columns]

In [0]:
X = train.iloc[:, [2,4,5,12]].values
X_test = test.iloc[:, [1,3,4,11]].values

y = train.iloc[:, 1].values
y_test=gs.iloc[:, [1]].values

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 1] = labelencoder.fit_transform(X[:, 1])
labelencoder1 = LabelEncoder()
X_test[:, 1] = labelencoder1.fit_transform(X_test[:, 1])

In [22]:
classifier = Sequential()
#Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu',input_dim = 4)) 
classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu')) 
#classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu'))
#Addind the output layer
classifier.add(Dense(output_dim = 1,init = 'uniform', activation = 'sigmoid')) 
#Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# Fitting the ANN to the Training set
classifier.fit(X,y,batch_size = 10,epochs = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=4, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  import sys


Epoch 1/100
891/891 [==============================] - 0s 488us/step - loss: 0.6879 - acc: 0.6105
Epoch 2/100
891/891 [==============================] - 0s 128us/step - loss: 0.6714 - acc: 0.6162
Epoch 3/100
891/891 [==============================] - 0s 131us/step - loss: 0.6611 - acc: 0.6162
Epoch 4/100
891/891 [==============================] - 0s 128us/step - loss: 0.6545 - acc: 0.6162
Epoch 5/100
891/891 [==============================] - 0s 123us/step - loss: 0.6485 - acc: 0.6162
Epoch 6/100
891/891 [==============================] - 0s 128us/step - loss: 0.6411 - acc: 0.6162
Epoch 7/100
891/891 [==============================] - 0s 124us/step - loss: 0.6317 - acc: 0.6162
Epoch 8/100
891/891 [==============================] - 0s 127us/step - loss: 0.6222 - acc: 0.6162
Epoch 9/100
891/891 [==============================] - 0s 122us/step - loss: 0.6080 - acc: 0.6162
Epoch 10/100
891/891 [==============================] - 0s 123us/step - loss: 0.5944 - acc: 0.6162
Epoch 11/100
891/89

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
y_pred = (y_pred>0.5)

In [26]:
y_pred

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[264,   2],
       [  9, 143]])